export const GAME_STATES = {
  PLAYING: 'PLAYING',
  PAUSED: 'PAUSED',
  VICTORY_SEQUENCE: 'VICTORY_SEQUENCE',
  VICTORY: 'VICTORY',
  GAME_OVER: 'GAME_OVER',
}

export const OVERHEAT = {
  perShot: 0.28,
  passiveCooling: 0,
  overheatCooling: 0.7,
  warningThreshold: 0.5,
  lockDuration: 1.5,
  coolantReduction: 0.6,
  warningAudioFreq: 660,
  warningAudioInterval: 0.45,
  lockAudioFreq: 100,
  blockAudioFreq: 120,
  coolantAudioFreq: 1320,
}

export const VICTORY_SEQUENCE = {
  duration: 4.5,
  cameraApproachSeconds: 1.5,
  cameraHoldSeconds: 2.5,
  cameraExitSeconds: 0.5,
  cameraFinal: { x: 0, y: 7, z: 34 },
  cameraLookAt: { x: 0, y: 4, z: 0 },
  pulseWaves: 5,
  pulseInterval: 0.85,
  pulseStartScale: 18,
  pulseEndScale: 580,
  pulseDuration: 1.3,
  pulseOpacity: 0.92,
  pulseColors: ['#FFD700', '#7DF9FF', '#FFD700', '#7DF9FF', '#FFFFFF'],
  fogStartDensity: 0.018,
  fogEndDensity: 0.0022,
  ambientBoost: 1.6,
  audioTones: [
    { freq: 220, duration: 0.6, delay: 0.0, type: 'sine' },
    { freq: 330, duration: 0.6, delay: 0.85, type: 'sine' },
    { freq: 440, duration: 0.6, delay: 1.7, type: 'sine' },
    { freq: 660, duration: 1.2, delay: 2.55, type: 'triangle' },
    { freq: 880, duration: 1.8, delay: 3.45, type: 'sine' },
  ],
}

export const GLACIES_COLORS = {
  cyan: '#7DF9FF',
  deepIce: '#082033',
  iceLine: '#9DEFFF',
  lanternGold: '#FFD700',
  anomalyPurple: '#7B2CFF',
  darkness: '#02070D',
}

export const ARENA = {
  radius: 360,
  visualSize: 820,
  safeSpawnRadius: 38,
}

export const TERRAIN = {
  propCount: 52,
  placementAttempts: 760,
  minObjectGap: 5.5,
  activeShadowDistance: 96,
}

export const TOWER_LAYOUT = [
  { x: -95, z: -130 },
  { x: 120, z: -95 },
  { x: 20, z: 145 },
]

export const TOWER_VISUAL = {
  asset: '/models/objects/darkTower.glb',
  modelScale: 5,
  radius: 10,
  height: 34,
  protectedRadius: 30,
  hitRadius: 14,
  hp: 6,
  hpBarWidth: 18,
  hpBarHeight: 1.6,
  hpBarY: 33,
}

export const PROJECTILE = {
  speed: 118,
  lifetime: 1.85,
  fireRate: 0.32,
  radius: 0.9,
  damage: 1,
  poolSize: 24,
}

export const DRONE = {
  asset: '/models/objects/defending_drone.glb',
  perTower: 2,
  hp: 2,
  hitRadius: 2.6,
  hpBarWidth: 7,
  hpBarHeight: 0.75,
  hpBarYOffset: 5.2,
  guardRadius: 28,
  guardSpread: 0.74,
  guardHeight: 15.5,
  guardDriftRadius: 4.6,
  guardStrafeSpeed: 1.15,
  modelScale: 1.9,
  fireRange: 132,
  fireRate: 1.45,
  projectileSpeed: 58,
  projectileLifetime: 3.1,
  projectileRadius: 0.72,
  projectileDamage: 8,
  projectilePoolSize: 32,
}

export const DRONE_STATES = {
  PASSIVE: 'PASSIVE',
  ALERT: 'ALERT',
  AGGRESSIVE: 'AGGRESSIVE',
  ENRAGED: 'ENRAGED',
}

export const DRONE_AI = {
  passive: {
    chaseSmoothing: 1.6,
    fireRateMul: 0,
    projectileSpeedMul: 0.85,
    driftMul: 1.0,
    approachMul: 0.0,
    predictive: false,
    burstCount: 0,
    hoverYOffset: 0,
  },
  alert: {
    chaseSmoothing: 2.4,
    fireRateMul: 0.45,
    projectileSpeedMul: 0.95,
    driftMul: 0.7,
    approachMul: 0.4,
    predictive: false,
    burstCount: 0,
    hoverYOffset: 0,
  },
  aggressive: {
    chaseSmoothing: 3.4,
    fireRateMul: 1.0,
    projectileSpeedMul: 1.05,
    driftMul: 0.4,
    approachMul: 0.85,
    predictive: true,
    burstCount: 0,
    hoverYOffset: -0.6,
  },
  enraged: {
    chaseSmoothing: 5.2,
    fireRateMul: 1.55,
    projectileSpeedMul: 1.25,
    driftMul: 0.15,
    approachMul: 1.3,
    predictive: true,
    burstCount: 3,
    hoverYOffset: -1.8,
  },
  transition: {
    alertDistance: 55,
    aggressiveDistance: 30,
    disengageDistance: 65,
    towerHurtThreshold: 0.55,
    towerCriticalThreshold: 0.28,
    towerRecoverThreshold: 0.4,
    stateHysteresis: 0.5,
  },
}

export const DRONE_GLOW = {
  textureSize: 128,
  color: '#7B2CFF',
  baseSize: 5.5,
  pulseSpeed: 1.6,
  pulseAmount: 0.08,
  hitFlashBoost: 0.55,
  yOffset: 0.0,
}

export const BOOST_CRYSTAL = {
  count: 6,
  collectRadius: 8.5,
  recharge: 0.42,
  modelScale: 2.1,
  y: 0.22,
  animateDistance: 160,
  layout: [
    { x: -160, z: -42 },
    { x: -135, z: 92 },
    { x: -48, z: -205 },
    { x: 82, z: 204 },
    { x: 164, z: 42 },
    { x: 190, z: -148 },
  ],
}

export const PHYSICS = {
  acceleration: 30,
  reverseAcceleration: 18,
  turnSpeed: 2.45,
  baseFriction: 0.34,
  driftFriction: 0.06,
  lateralStabilization: 1.25,
  driftStabilization: 0.12,
  maxSpeed: 62,
  boostImpulse: 31,
  boostCooldown: 0.75,
  boundaryBounce: 0.38,
  obstacleBounce: 0.58,
  shipRadius: 5.2,
  impactDamageMinSpeed: 11,
  impactDamageMultiplier: 0.19,
  collisionDamageCooldown: 0.55,
  projectileSpawnForward: 11.5,
}

export const CAMERA = {
  height: 62,
  backDistance: 46,
  lookAhead: 58,
  lookHeight: 1.6,
  smoothing: 6.4,
  fov: 58,
}

export const LIGHTING = {
  fogColor: '#01070d',
  fogDensity: 0.0105,
  ambientColor: '#5fe7ff',
  ambientIntensity: 0.004,
  hemisphereColor: '#96f5ff',
  hemisphereGroundColor: '#01070d',
  hemisphereIntensity: 0.008,
  directionalColor: '#c6fbff',
  directionalIntensity: 0,
  fillColor: '#9defff',
  fillIntensity: 0,
  lanternColor: '#F6FEFF',
  lanternCoreColor: '#FFFFFF',
  lanternWarmColor: '#EAFBFF',
  lanternIntensity: 16,
  lanternDistance: 135,
  lanternAngle: 54,
  lanternPenumbra: 0.95,
  lanternDecay: 1.15,
  lanternTargetDistance: 24,
  lanternTargetDrop: 0.86,
  lanternSourceY: 0.08,
  lanternSourceZ: -1.05,
  shadowMapSize: 1024,
  shadowCameraNear: 1,
  shadowCameraFar: 150,
  shadowBias: -0.00016,
  beamGroundY: 0.075,
  groundPoolWidth: 22,
  groundPoolLength: 28,
  groundPoolOpacity: 1.08,
  groundPoolBloomOpacity: 0.55,
  groundContactLightIntensity: 4.5,
  groundContactLightDistance: 58,
  beamTilt: 5.5,
  beamHeight: 24,
  beamNearWidth: 0.75,
  beamRadius: 8.5,
  beamOpacity: 0.85,
  beamAirY: 0.78,
  beamApexY: 0.08,
  beamApexZ: -1.05,
  shipGlowIntensity: 1.1,
  shipGlowDistance: 13,
}

export const LIGHT_PHASES = [
  {
    fogDensity: 0.0062,
    ambientIntensity: 0.075,
    hemisphereIntensity: 0.14,
    directionalIntensity: 0.045,
    fillIntensity: 0.06,
    iceEmissiveIntensity: 0.11,
    crackOpacity: 0.24,
    frostOpacity: 0.08,
    boundaryOpacity: 0.34,
    lanternScale: 1.08,
    droneHaloOpacity: 0.32,
    transitionSpeed: 1.2,
  },
  {
    fogDensity: 0.0046,
    ambientIntensity: 0.16,
    hemisphereIntensity: 0.25,
    directionalIntensity: 0.11,
    fillIntensity: 0.17,
    iceEmissiveIntensity: 0.24,
    crackOpacity: 0.42,
    frostOpacity: 0.16,
    boundaryOpacity: 0.56,
    lanternScale: 1.03,
    droneHaloOpacity: 0.5,
    transitionSpeed: 1.12,
  },
  {
    fogDensity: 0.0034,
    ambientIntensity: 0.28,
    hemisphereIntensity: 0.38,
    directionalIntensity: 0.22,
    fillIntensity: 0.3,
    iceEmissiveIntensity: 0.42,
    crackOpacity: 0.62,
    frostOpacity: 0.28,
    boundaryOpacity: 0.78,
    lanternScale: 0.98,
    droneHaloOpacity: 0.68,
    transitionSpeed: 1.05,
  },
  {
    fogDensity: 0.0016,
    ambientIntensity: 0.62,
    hemisphereIntensity: 0.68,
    directionalIntensity: 0.42,
    fillIntensity: 0.48,
    iceEmissiveIntensity: 0.76,
    crackOpacity: 0.88,
    frostOpacity: 0.5,
    boundaryOpacity: 1,
    lanternScale: 0.9,
    droneHaloOpacity: 0.95,
    transitionSpeed: 0.9,
  },
]

export const SHIP_BEAM_STYLES = {
  'keeper-default': {
    lanternColor: '#F6FEFF',
    glowColor: '#EAFBFF',
    coreColor: '#FFFFFF',
    edgeColor: '#C7F8FF',
    groundColor: '#F2FEFF',
    projectileColor: '#FFD36A',
    coreWidth: 0.42,
    intensity: 1.0,
    pulseSpeed: 1,
  },
  'keeper-scout': {
    lanternColor: '#F8FEFF',
    glowColor: '#ECFCFF',
    coreColor: '#FFFFFF',
    edgeColor: '#CFF9FF',
    groundColor: '#F4FEFF',
    projectileColor: '#FF7DE8',
    coreWidth: 0.5,
    intensity: 1.18,
    pulseSpeed: 1.28,
  },
  'keeper-relic': {
    lanternColor: '#FAFEFF',
    glowColor: '#F0FDFF',
    coreColor: '#FFFFFF',
    edgeColor: '#D9FBFF',
    groundColor: '#F8FEFF',
    projectileColor: '#B7D7FF',
    coreWidth: 0.34,
    intensity: 0.94,
    pulseSpeed: 0.78,
  },
}

export const ICE_PROP_PROFILES = [
  {
    asset: '/models/objects/ice_crystal.glb',
    family: 'ice',
    role: 'medium-crystal',
    weight: 16,
    targetRadius: { min: 6, max: 17 },
    y: 0.04,
    colliderPadding: 0.96,
    contactShadowScale: 1.1,
    tint: '#cdfaff',
    tintStrength: 0.48,
    emissive: '#0a7d8f',
    emissiveIntensity: 0.15,
  },
  {
    asset: '/models/objects/ice_crystal2.glb',
    family: 'ice',
    role: 'large-crystal',
    weight: 10,
    targetRadius: { min: 10, max: 25 },
    y: 0.04,
    colliderPadding: 0.98,
    contactShadowScale: 1.18,
    tint: '#d8fdff',
    tintStrength: 0.5,
    emissive: '#0a7d8f',
    emissiveIntensity: 0.16,
  },
  {
    asset: '/models/objects/ice_crystal3.glb',
    family: 'ice',
    role: 'sharp-crystal',
    weight: 14,
    targetRadius: { min: 7, max: 18 },
    y: 0.04,
    colliderPadding: 0.96,
    contactShadowScale: 1.08,
    tint: '#c8fbff',
    tintStrength: 0.45,
    emissive: '#0a7186',
    emissiveIntensity: 0.14,
  },
  {
    asset: '/models/objects/ice_rock.glb',
    family: 'ice',
    role: 'ice-boulder',
    weight: 20,
    targetRadius: { min: 9, max: 28 },
    y: 0.1,
    colliderPadding: 0.96,
    contactShadowScale: 1.22,
    tint: '#9bd7ee',
    tintStrength: 0.44,
    emissive: '#042c3d',
    emissiveIntensity: 0.055,
  },
  {
    asset: '/models/objects/kenney-nature/rock_largeA.glb',
    family: 'kenney-rock',
    role: 'rounded-boulder',
    weight: 8,
    targetRadius: { min: 7, max: 20 },
    y: 0.02,
    colliderPadding: 1.08,
    contactShadowScale: 1.3,
    tint: '#a9dff0',
    tintStrength: 0.62,
    emissive: '#042c3d',
    emissiveIntensity: 0.04,
  },
  {
    asset: '/models/objects/kenney-nature/rock_largeB.glb',
    family: 'kenney-rock',
    role: 'rounded-boulder',
    weight: 8,
    targetRadius: { min: 8, max: 21 },
    y: 0.02,
    colliderPadding: 1.08,
    contactShadowScale: 1.3,
    tint: '#a7d8e9',
    tintStrength: 0.6,
    emissive: '#042c3d',
    emissiveIntensity: 0.04,
  },
  {
    asset: '/models/objects/kenney-nature/rock_tallA.glb',
    family: 'kenney-rock',
    role: 'tall-boulder',
    weight: 6,
    targetRadius: { min: 7, max: 18 },
    y: 0.02,
    colliderPadding: 1.1,
    contactShadowScale: 1.16,
    tint: '#b5e5f2',
    tintStrength: 0.62,
    emissive: '#042c3d',
    emissiveIntensity: 0.035,
  },
  {
    asset: '/models/objects/kenney-nature/rock_tallB.glb',
    family: 'kenney-rock',
    role: 'tall-boulder',
    weight: 6,
    targetRadius: { min: 6, max: 16 },
    y: 0.02,
    colliderPadding: 1.1,
    contactShadowScale: 1.16,
    tint: '#b5e5f2',
    tintStrength: 0.62,
    emissive: '#042c3d',
    emissiveIntensity: 0.035,
  },
  {
    asset: '/models/objects/kenney-nature/stone_largeA.glb',
    family: 'kenney-stone',
    role: 'stone-boulder',
    weight: 8,
    targetRadius: { min: 7, max: 19 },
    y: 0.02,
    colliderPadding: 1.08,
    contactShadowScale: 1.28,
    tint: '#b7e8f5',
    tintStrength: 0.58,
    emissive: '#043141',
    emissiveIntensity: 0.035,
  },
]

export const ICE_COLLISION_PROFILES = {
  '/models/objects/ice_crystal.glb': {
    radiusXZ: 3.98,
    center: { x: 0.08, z: 0.22 },
  },
  '/models/objects/ice_crystal2.glb': {
    radiusXZ: 6.42,
    center: { x: 0.64, z: 0.72 },
  },
  '/models/objects/ice_crystal3.glb': {
    radiusXZ: 4.51,
    center: { x: 0.14, z: 0.09 },
  },
  '/models/objects/ice_rock.glb': {
    radiusXZ: 7.72,
    center: { x: -0.14, z: 0.68 },
  },
  '/models/objects/kenney-nature/cliff_rock.glb': {
    radiusXZ: 0.5,
    center: { x: 0, z: 0.42 },
  },
  '/models/objects/kenney-nature/cliff_stone.glb': {
    radiusXZ: 0.5,
    center: { x: 0, z: 0.42 },
  },
  '/models/objects/kenney-nature/rock_largeA.glb': {
    radiusXZ: 0.51,
    center: { x: 0, z: 0 },
  },
  '/models/objects/kenney-nature/rock_largeB.glb': {
    radiusXZ: 0.51,
    center: { x: 0, z: 0 },
  },
  '/models/objects/kenney-nature/rock_tallA.glb': {
    radiusXZ: 0.49,
    center: { x: 0, z: 0 },
  },
  '/models/objects/kenney-nature/rock_tallB.glb': {
    radiusXZ: 0.39,
    center: { x: 0, z: 0 },
  },
  '/models/objects/kenney-nature/stone_largeA.glb': {
    radiusXZ: 0.51,
    center: { x: 0, z: 0 },
  },
}

export const HUD_SEGMENTS = 8
